# Generated by Django 5.1.5 on 2025-01-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Terms",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("use", models.TextField()),
                ("privacy_policy", models.TextField()),
            ],
        ),
    ]
