# Generated by Django 5.1.5 on 2025-01-23 09:27

import django.utils.timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("term", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="terms",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
