# Generated by Django 5.1.5 on 2025-01-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("next_bill_date", models.DateTimeField()),
                ("remaining_bill_date", models.DateTimeField()),
                ("auto_renew", models.BooleanField(default=False, null=True)),
                (
                    "cancelled_reason",
                    models.CharField(
                        choices=[
                            ("expensive", "가격이 비싸서"),
                            ("quality", "퀄리티가 마음에 들지 않아서"),
                            ("slow_communication", "소통이 느려서"),
                            ("hire_full_time", "정직원을 구하는 것이 더 편해서"),
                            ("budget_cut", "회사 예산이 줄어들어서"),
                            ("other", "기타"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "other_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="기타 사유 (상세입력)",
                    ),
                ),
            ],
        ),
    ]
