# Generated by Django 5.1.5 on 2025-02-03 07:15

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0001_initial"),
        ("subscription", "0002_subs_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="subhistories",
            name="plan",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="plan.plans"
            ),
            preserve_default=False,
        ),
    ]
