# Generated by Django 5.1.5 on 2025-02-04 07:16

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_billingkey"),
        ("subscription", "0003_subhistories_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="subs",
            name="billing_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.billingkey",
            ),
        ),
    ]
