# Generated by Django 5.1.6 on 2025-02-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0004_subs_billing_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subs",
            name="cancelled_reason",
        ),
        migrations.RemoveField(
            model_name="subs",
            name="other_reason",
        ),
        migrations.AddField(
            model_name="subhistories",
            name="cancelled_reason",
            field=models.CharField(
                choices=[
                    ("expensive", "가격이 비싸서"),
                    ("quality", "퀄리티가 마음에 들지 않아서"),
                    ("slow_communication", "소통이 느려서"),
                    ("hire_full_time", "정직원을 구하는 것이 더 편해서"),
                    ("budget_cut", "회사 예산이 줄어들어서"),
                    ("other", "기타"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subhistories",
            name="other_reason",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="기타 사유 (상세입력)",
            ),
        ),
    ]
