# Generated by Django 5.1.6 on 2025-02-24 14:49

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0002_alter_plans_is_active"),
        ("subscription", "0006_alter_subhistories_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subhistories",
            name="plan",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="plan.plans"
            ),
        ),
        migrations.AlterField(
            model_name="subhistories",
            name="sub",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscription.subs",
            ),
        ),
        migrations.AlterField(
            model_name="subhistories",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
