# Generated by Django 5.1.5 on 2025-02-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pays",
            name="imp_uid",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
