# Generated by Django 5.1.5 on 2025-02-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_pays_imp_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pays",
            name="merchant_uid",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
