# Generated by Django 5.1.6 on 2025-02-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_billingkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingkey",
            name="card_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="billingkey",
            name="card_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
