# Generated by Django 5.1.6 on 2025-02-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_billingkey_card_name_billingkey_card_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="pays",
            name="refund_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
