# Generated by Django 5.1.6 on 2025-02-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_pays_refund_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="pays",
            name="refund_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
