# Generated by Django 5.1.6 on 2025-02-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_pays_refund_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pays",
            name="refund_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
