# Generated by Django 5.1.5 on 2025-02-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plans",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("plan_name", models.CharField(max_length=100)),
                ("price", models.BigIntegerField()),
                (
                    "period",
                    models.CharField(
                        choices=[("monthly", "월간"), ("yearly", "연간")], max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
