# Generated by Django 5.1.6 on 2025-02-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plans",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
