# Generated by Django 5.1.5 on 2025-01-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreements",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
