# Generated by Django 5.1.5 on 2025-01-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_agreements_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="provider",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
