# Generated by Django 5.1.5 on 2025-02-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_customuser_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="img_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
