# Generated by Django 5.1.6 on 2025-02-06 17:49

import django.core.validators

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="전화번호는 '010-1234-5678' 형식으로 입력해주세요.",
                        regex="^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$",
                    )
                ],
            ),
        ),
    ]
