# Generated by Django 5.1.6 on 2025-02-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreements",
            name="terms_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
