# Generated by Django 5.1.6 on 2025-02-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_agreements_terms_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="sub_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("paused", "Paused"),
                    ("none", "None"),
                    ("refund_pending", "환불 대기"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
