# Generated by Django 5.1.6 on 2025-02-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_customuser_email_alter_customuser_is_staff"),
        ("user", "0008_alter_customuser_sub_status"),
    ]

    operations = []
