# Generated by Django 5.1.6 on 2025-02-23 18:49

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_merge_20250221_2021"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalReason",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_withdrawal_reasons",
            },
        ),
    ]
