# Generated by Django 5.1.6 on 2025-02-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_withdrawalreason_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_deletion_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
