# Generated by Django 5.1.6 on 2025-02-22 03:32

import django.utils.timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tally", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tally",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tally",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tally",
            name="form_name",
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
